# Generated by Django 2.2.4 on 2019-09-25 10:58

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=120)),
                ('artist_label', models.CharField(max_length=120)),
                ('artist_country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=120)),
                ('label_address', models.TextField(max_length=120)),
                ('label_genre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(default='Unknown Track', max_length=120)),
                ('track_artist', models.CharField(default='Unknown Artist', max_length=120)),
                ('track_album', models.CharField(default='Unknown Album', max_length=120)),
                ('track_genre', models.CharField(max_length=100)),
                ('track_year', models.IntegerField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
    ]
