# Generated by Django 2.2.4 on 2019-09-25 11:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_country',
            field=django_countries.fields.CountryField(default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_country',
            field=django_countries.fields.CountryField(default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Artist'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(default='Unknown Album', max_length=120)),
                ('album_year', models.IntegerField(validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('album_genre', models.CharField(max_length=120)),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Artist')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
