# Generated by Django 2.2.4 on 2019-09-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190925_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
