# Generated by Django 2.2.4 on 2019-09-25 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_track_track_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_year',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_year',
            field=models.IntegerField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
