# Generated by Django 2.2.4 on 2019-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20190925_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_year',
            field=models.IntegerField(),
        ),
    ]
