# Generated by Django 2.2.5 on 2019-09-27 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190925_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Album'),
        ),
    ]
