# Generated by Django 2.2.5 on 2019-09-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190927_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='track_album',
        ),
    ]
