# Generated by Django 2.2.5 on 2019-09-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_track_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_album',
            field=models.ForeignKey(blank=True, default='Unknown Album', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='manager.Album'),
        ),
    ]
