# Generated by Django 2.2.5 on 2019-09-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190927_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_album',
            field=models.CharField(default='Unknown Album', max_length=120),
        ),
    ]
